# version: "3.8"
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network
    container_name: mongodb

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongodb
    networks:
      - mongo-network
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
    ports:
      - 9010:8081
    restart: always
    container_name: mongo-express

volumes:
  mongo-data:

networks:
  mongo-network:
    driver: bridge
